### PR TITLE
Adds ansible.compatiblity_mode statement to Vagrantfiles

### PR DESCRIPTION
**Pull request by kevinbowen777**
Adds the ansible.compatibility_mode = "2.0" statement to Vagrantfiles where Ansible provisioning occurs.

### CODE REVIEW

**Comment by geerlingguy** [comment]
So, I agree with this PR in practice, but in my hopes and dreams, I want it to not be required at all to get rid of the annoying warning you get in Vagrant's output.

Therefore, I've opened the following upstream issue and would like to leave a little time to see if this can just be resolved upstream: https://github.com/hashicorp/vagrant/issues/11419

**Comment by kevinbowen777** [comment]
I concur. Thanks for opening up an issue upstream. I was mainly aiming for consistency within your book's repos. Appreciate the quick response.

**Comment by geerlingguy** [comment]
@kevinbowen777 - Laziness wins the day again! It looks like 2.2.8 includes the fix for the annoying compatibility mode warning (by changing it to 'INFO' level so it doesn't display in normal output).

**Comment by geerlingguy** [comment]
See commit above — I'm just removing it from the one place it exists. Thanks for this PR though!

**Pull request closed without merging**
