### PR TITLE
update the cache after adding the php repo

### PR DESCRIPTION
**Pull request by arbabnazar**
@geerlingguy , I think we need to update the cache after adding the php repo.
We need to remove this ''cache_valid_time=3600" because after adding the php custom repo, it will not update even we try to update the cache, reason that have set the cache valid time to 1hr. Thanks

### CODE REVIEW

**Comment by geerlingguy** [comment]
Actually, this should be worked a little differently; the `update_cache=yes` should go on the earlier `apt_repository` task, which tells Ansible to update the cache only if the repository has been added (which is the correct behavior here). Then we can leave the other update_cache in there with it's 3600 cache lifetime value to speed up immediate re-runs, and also help future deployments.

Can you adjust the PR to do it that way?

**Comment by arbabnazar** [comment]
@geerlingguy, can you please check the modification. Thanks

**Comment by geerlingguy** [comment]
Perfect!

**Comment by arbabnazar** [comment]
Thanks

**Pull request merged**
