### PR TITLE
Fix cache-max-age CLI option and typo

### PR DESCRIPTION
**Pull request by charignon**
This PR fixes two issues with caching:
1 `self.is_cache_valid` was used instead of the method call, it always returned
true instead of checking the cache validity. I added the parentheses.
2  The command-line option: `--cache-max_age` was never used anywhere. So the max age for the cache could only be specified in a config file. I added code to handle the command-line option.

I checked several scenarios with and without `--force-cache` and by removing the cache file, everything is working like I would expect now.
cc @geerlingguy

### CODE REVIEW

**Comment by geerlingguy** [comment]
That failure is actually due to Node.js being screwed up by some upstream EPEL changes. I'll try to take a look at this soon!

**Comment by charignon** [comment]
What is the link between this and node JS I don't quite understand ?

**Comment by charignon** [comment]
Oh you meant the Travis failure ?

**Comment by geerlingguy** [comment]
Yeah, sorry :)

**Comment by geerlingguy** [comment]
In this case I'm also going to defer to the upstream Ansible digital_ocean.py script which this was originally taken from. I'm going to try to get things updated from there. Any changes/improvements should be submitted upstream: https://github.com/ansible/ansible/blob/devel/contrib/inventory/digital_ocean.py

**Pull request closed without merging**
